version: "3.2"
services:
  wanmonitor:
    image: wanmonitor
    build:
      context: './'
    ports:
      - 5005:5005 # remote debugging port
    volumes:
      - ./src:/root/src/
      - ./build:/root/target/
    container_name: wanmonitor
